name: doctor_booking_app_with_flutter_and_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  geolocator: ^8.0.0
  geocoding: ^2.0.0
  hmssdk_flutter: 1.9.14
  permission_handler: ^10.2.0
  http: ^1.0.0 # veya http: 0.13.4 dene
  provider: 6.0.2
  draggable_widget: 2.0.0
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  image_picker: ^0.8.4+2
  video_player: ^2.1.15


  cupertino_icons: 1.0.2 # veya cupertino_icons: ^1.0.6 dene
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  models:
    path: packages/models
  flutter_bloc: ^8.1.4 
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 #veya flutter_lints: ^1.0.0 dene

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"































